<a href="https://colab.research.google.com/github/jfas84/estudos-de-inteligencia-artificial/blob/main/curso-IA/python-basico/10_matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrizes

Aqui faço a importação do numpy para utilizar os arrays.

Para chamar o array em numpy temos que passar o apelido + array()

np.array()

In [4]:
# Tradução -> importe numpy 'com o apelido' np -> logo, sempre que precisamos utilizar algo dessa biblioteca usamos o np.

import numpy as np

In [ ]:
# Aqui defino uma matriz de 2 linhas com 3 colunas.

matriz = np.array([[2, 3, 1], 
                   [4, 5, 7]])

In [ ]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [ ]:
# shape -> serve para verificar como é a matriz, retornando quantas linhas e quantas colunas.

matriz.shape

(2, 3)

In [ ]:
# Para retornar determinado item de uma matriz temos que passar 2 argumentos, o primeiro é a linha e o segundo a coluna, se passo apenas 1 argumento será retornado toda a linha.

matriz[0]

array([2, 3, 1])

In [ ]:
matriz[1]

array([4, 5, 7])

In [ ]:
matriz[0][2]

1

In [ ]:
matriz[1][2]

7

In [ ]:
matriz.shape

(2, 3)

In [ ]:
for i in range(matriz.shape[0]):
  print(matriz[i])
  for j in range(matriz.shape[1]):
    print(matriz[i][j])  

[2 3 1]
2
3
1
[4 5 7]
4
5
7


In [9]:
# somando todos os elementos dentro do array

exec = np.array([[3,4,1], [3,1,5]])
soma = 0
for i in range(exec.shape[0]):
  for j in range(exec.shape[1]):
    soma += exec[i][j]

print(soma)

17
